### ISSUE TITLE
update time

### ISSUE THREAD

**Issue by huizebruin** [simonhq/accu_allergies#13]
How can i change the update time?
and how can i do the update variables?

```alias: pollen update
description: ''
trigger:
  - platform: time
    at: '12:00'
  - platform: time
    at: '18:00'
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.get_allergies_data
    data: {}
mode: single
```
I made this but its not updating.

**Comment by simonhq** [comment]
Hi Huizebruin,

The code works like this:

The get allergies flag trigger downloads and stores the data in a local data file - it does this automatically at 5.30am each day.

The load allergies flag trigger read from the local data file and updates the sensors (and thus the ui). 

Your automation above is working correctly but is only doing have the job, create a second one that triggers when the

```
entity_id: input_boolean.get_allergies_data
```
turns off, and then turn on the load allergies flag (what ever you have called yours) and it should then update the ui.

Hope this helps

Simon.

**Comment by huizebruin** [comment]
like this?

```
alias: pollen update
description: ''
trigger:
  - platform: time_pattern
    minutes: '59'
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id:
        - input_boolean.get_allergies_data
        - input_boolean.reset_allergies_sensor
    data: {}
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
        - input_boolean.get_allergies_data
        - input_boolean.reset_allergies_sensor
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
        - input_boolean.get_allergies_data
mode: single
```

**Comment by simonhq** [comment]
Hi Huizebruin,

I would expect something more like this:

```
description: ''
trigger:
  - platform: time
    at: '12:00'
  - platform: time
    at: '18:00'
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.get_allergies_data
    data: {}
mode: single

description: ''
trigger:
  - platform: state
    entity_id: input_boolean.get_allergies_data
    to: off
condition: []
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.load_allergies_data
    data: {}
mode: single
```

This will then do the following:

the first automation will download the new data into the local file at midday and at 6pm.
the second automation will watch the flag for conducting the download, and when it finishes it will reload the new data into the ui.

hope this helps

Simon
