### ISSUE TITLE
No data anymore

### ISSUE THREAD

**Issue by Ricks88** [simonhq/accu_allergies#17]
Hi Simon :P 

Something has changed and i get no data anymore:

https://www.accuweather.com/nl/nl/posterholt/248858/weather-forecast/248858
https://www.accuweather.com/en/nl/posterholt/248858/weather-forecast/248858

I think it is set to the new "APRIL22" now, but still gives me no data anymore :(

Could you please take a look again?

Rick

**Comment by simonhq** [comment]
Hi Rick,

The website seems to be the same, can you post your apps.yaml block for this app please.

Simon.

**Comment by huizebruin** [comment]
Here also No data anymore.
![image](https://user-images.githubusercontent.com/62996429/218223048-182ef31e-0a88-481e-b4fa-c9be3865e4b2.png)

```
with the  WEB_VER: "" # or use "APRIL22"
```
april22 version doesn't work at Holland, then i don't get any sensors anymore.
an without i only get the Air Quality Today & Air Quality Tomorrow

**Comment by huizebruin** [comment]
a i found it.
@Ricks88 

```
accu_allergies:
   module: accu_allergies
   class: Get_Accu_Allergies
   ACC_FILE: "./allergies"
   ACC_FLAG: "input_boolean.get_allergies_data"
   DEB_FLAG: "input_boolean.reset_allergies_sensor"
   URL_ID: "248858"
   URL_CITY: "posterholt"
   URL_COUNTRY: "NL"
   URL_LANG: "NL"
   URL_POSTCODE: ""
   WEB_VER: "APRIL22" # or use "APRIL22"
```

```
- sensor.acc_data_last_sourced
— sensor.acc_boompollen_today
— sensor.acc_ambrosiapollen_today
— sensor.acc_schimmel_today
— sensor.acc_graspollen_today
— ensor.acc_huisstofmijt_today
— sensor.acc_artritis_today
— sensor.acc_sinusdruk_today
— sensor.acc_verkoudheid_today
— sensor.acc_griep_today
— sensor.acc_migraine_today
— sensor.acc_astma_today
— sensor.acc_vissen_today
— sensor.acc_hardlopen_today
— sensor.acc_golf_today
— sensor.acc_fietsen_today
— sensor.acc_strand_en_zwembad_today
— sensor.acc_sterrenkijken_today
— sensor.acc_wandelen_today
— sensor.acc_vliegreizen_today
— sensor.acc_autorijden_today
— sensor.acc_grasmaaien_today
— sensor.acc_composteren_today
— sensor.acc_buiten_eten_today
— sensor.acc_muggen_today
— sensor.acc_ongedierte_in_huis_today
— sensor.acc_ongedierte_buiten_today
— sensor.acc_air_today
— sensor.acc_air_tomorrow
```
Now u get Dutch tekst of the sensors.
I had written nl in small type but must be capital NL now its working again.
