### ISSUE TITLE
Everything appears as unknown

### ISSUE THREAD

**Issue by frayberen** [simonhq/accu_allergies#20]
Same problem. Everything keeps showing up as unknown and I've already tried every way I can think of... Any light...?

Thanks!!
![Captura de pantalla 2023-07-28 a las 18 17 11](https://github.com/simonhq/accu_allergies/assets/49491611/e5705fba-0081-40e9-a378-3cad39f7865a)
![Captura de pantalla 2023-07-28 a las 18 15 55](https://github.com/simonhq/accu_allergies/assets/49491611/d5b61379-66f3-43e9-b028-0781fb8b598e)

**Comment by simonhq** [comment]
Hi Fraybean,

You need to uncomment the "APRIL22" i.e., remove the # so that the correct version of the code is getting the data.

Thanks

Simon.

**Comment by frayberen** [comment]
I have also tried uncommenting and I can't do it either. The input_boolean.get_allergies_data does not return, it gets stuck.

**Comment by simonhq** [comment]
Can you post the appdaemon logs of what it is saying when it runs please.

**Comment by simonhq** [comment]
Hey Frayberen,

I would also suggest changing your block to this:

```
accu_allergies:
  module: accu_allergies
  class: Get_Accu_Allergies
  ACC_FILE: "./allergies"
  ACC_FLAG: "input_boolean.get_allergies_data"
  DEB_FLAG: "input_boolean.reset_allergies_sensor"
  URL_ID: "1457283"
  URL_CITY: "maria-de-huerva"
  URL_COUNTRY: "es"
  URL_LANG: "es"
  URL_POSTCODE: ""
  WEB_VER: "APRIL22"
```

As in your url, you don't have a different postcode to your ID
